### ISSUE TITLE
Cannot find install.php

### ISSUE THREAD

**Issue by gogo9th** [yagoag/HouSplit#21]
Hi,

I'm trying to install your web application. However, your description says I have to run install.php and I cannot find it... Where is it?

**Comment by yagoag** [comment]
Hi @gogo9th 

Sorry about that! I remember having started writing this script, but I must have never pushed it to the repo.

Since it's been a while I have last touched the project and I can't seem to find it on my machine, I went ahead and created a small installation page which should allow you to create the first administrator account of the system.

I do not have a PHP setup at the moment, so I did not test it yet, I will try to to that over the weekend. In the meantime, if you want to test the script, it is on the `install-script` branch: https://github.com/yagoag/HouSplit/tree/install-script

You should be able to access it via `http://localhost/index.php?p=install` (changing the host name accordingly).

If you get a chance to try it out, would you care to reply back with the results?

Thanks!

**Comment by yagoag** [comment]
Resolved by #22 .
